# Game Configuration
width = 50
height = 25
tick_rate_ms = 200  # Initial speed

# Level Configuration
starting_level = 1
max_levels = 3
score_per_level = 5  # Score needed for each level (Level 1: 5, Level 2: 10, Level 3: 15)

# Obstacle Configuration
base_obstacles = 4
obstacles_per_level = 2
obstacle_sizes = [1, 2]

# Display Configuration
snake_char = "█"
food_char = "●"
border_char = "█"