# Game Configuration
width = 50    # Increased width
height = 25   # Increased height
tick_rate_ms = 100  # Speed of the snake

# Display Configuration
snake_char = "█"
food_char = "●"
border_char = "█"